name: Update State

on:
  push:
    branches:
      - main

jobs:
  update-state:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Wait for 10 minutes
        uses: actions/github-script@v4
        with:
          script: |
            const timeToWait = 420000; // 7 minutes in milliseconds
            await new Promise(resolve => setTimeout(resolve, timeToWait));

      - name: Read and update state file
        run: |
          sed -i 's/true/false/' state.txt
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add state.txt
          git commit -m "Update state from true to false" --author="GitHub Actions <actions@github.com>"
          git push
